ALTER TABLE TinyHouses ADD COLUMN Amenities TEXT NULL;
ALTER TABLE TinyHouses ADD COLUMN Beds INTEGER DEFAULT 1;
ALTER TABLE TinyHouses ADD COLUMN Photos TEXT NULL;
ALTER TABLE TinyHouses ADD COLUMN UpdatedAt DATETIME NULL;
ALTER TABLE TinyHouses ADD COLUMN Bathrooms INTEGER DEFAULT 1; 